name: CI pipeline

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: "Build node${{ matrix.node-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn --ignore-engines --frozen-lockfile --ignore-scripts
